apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      initContainers:
        - name: echo-init
          image: hashicorp/http-echo:latest
          command: ["sleep"]
          args: ["5"]
