resources:
  - ../base/

patches:
  - path: env-config.yaml
patchesStrategicMerge:
  - init-echo-container.yaml


replacements:
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.all.env.[name=K8S_CLUSTER_NAME].value
        options:
          create: true
configMapGenerator:
  - name: cluster-config
    literals:
      - CLUSTER_NAME=default-cluster  # 默认值