apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-multi
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            managed-by: ken
  template:
    metadata:
      name: '{{name}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/w564791/argo-test.git
        path: nginx/dev
        targetRevision: main
        kustomize:
          images:
            - nginx=nginx:latest
          patches:
            - target:
                kind: ConfigMap
                name: cluster-config.*  # 匹配生成的 ConfigMap
              patch: |
                - op: replace
                  path: /data/0/CLUSTER_NAME
                  value: '{{name}}'
      destination:
        server: '{{server}}'
        namespace: argo-cd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true