apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.repo.git  # 替换为你的 Git 仓库地址
    targetRevision: HEAD
    path: app/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
